model_params:
  name: 'VanillaVAE'
  in_channels: 1
  latent_dim: 50

exp_params:
  dataset: mnist
  data_path: "../../shared/Data/"
  img_size: 32
  batch_size: 64
  LR: 0.0001
  weight_decay: 0
  scheduler_gamma: 0.95

trainer_params:
  gpus: []
  max_epochs: 30

logging_params:
  save_dir: "logs/"
  best_model_dir: "trained_models/best_vae.model"
  name: "VanillaVAE"
  manual_seed: 1265
